require("plugins.git")
require("plugins.ui")
require("plugins.file-explorer")
require("plugins.treesitter")
require("plugins.completion")
require("plugins.fzf")
require("plugins.formatting")
require("plugins.linting")
-- require("plugins.mason")
require("plugins.lsp")
require("plugins.session")
require("plugins.mini")
require("plugins.aerial")
require("plugins.keymap-tools")
require("plugins.indent")
